### ISSUE TITLE
如何在md中注册组件？只能使用全局注册的组件吗？

### ISSUE THREAD

**Issue by fangzhioo** [LiangQuanQing/vite-plugin-md2vue2#1]
类似 `vite-plugin-md` ,可以在md中直接注册使用组件！

**Comment by LiangQuanQing** [comment]
暂时只能使用全局组件，`vite-plugin-md`中能怎么使用我还没仔细看过，之后会参考下对应的功能在新版本中发布

**Comment by LiangQuanQing** [comment]
已经在@2.0.4中支持

**Comment by LiangQuanQing** [comment]
It is already supported in version @2.0.4
