### ISSUE TITLE
局部和全局组件无法显示

### ISSUE THREAD

**Issue by shuaizai88** [LiangQuanQing/vite-plugin-md2vue2#8]
局部引入的时候直接把引入的代码显示出来了

**Comment by shuaizai88** [comment]
着急使用，而且全网只有你一个，希望给个联系方式：921888199@qq.com

**Comment by LiangQuanQing** [comment]
你好，我已经发现问题，预计今天内会进行修复

**Comment by LiangQuanQing** [comment]
你好，请提供一下可复现的最小化的仓库或者示例，方便修复

**Comment by shuaizai88** [comment]
实例发到您邮箱了，请注意查收，另外加了您qq了方便的话也帮忙通过下。

**Comment by LiangQuanQing** [comment]
已在2.0.8版本中修复，可替换使用，注意查看最新的readme文档
